### ISSUE TITLE
Sync movie ratings and add to watched history

### ISSUE THREAD

**Issue by Myonimato** [cecobask/imdb-trakt-sync#4]
Hey, I just stumbled across your project and it works amazing. I only got one little feature request:

Would it be possible to mark a movie as watched on Trakt when the rating from IMDb is synced? I now only got the rating synced but it's not in the history.

Best Regards

Nico

**Comment by Myonimato** [comment]
Update: it works like I wished. Just the first sync got a timeout and therefore the history wasn't written correctly. Case closed.

**Comment by rafae667** [comment]
I stumbled across the same problem. All the ratings are syncing but on Trakt are not marked as watched. I got the movies on ratings and not on history also.

**Comment by cecobask** [comment]
@rafae667, do you mind sending me a link to an IMDb item that you've rated and hasn't synced its rating or history to Trakt?
I tried with [The Godfather (1972)](https://www.imdb.com/title/tt0068646/) and it worked as expected 🤔 
I couldn't reproduce this issue...

**Comment by rafae667** [comment]
In my trakt account I have everything synced well. The ratings on IMDB went to the ratings in the Trakt.
But in the Trakt history, where the movies I've seen are, is empty. 
It isn't supposed to the rating movies to appear also in the Trakt history marked as seen?

**Comment by cecobask** [comment]
The way history is being synced is the following:
- you rate movies, shows and episodes on IMDb
- treating IMDb as the source of truth, `imdb-trakt-sync` would find the difference between your IMDb and Trakt ratings
- it will add and/or remove any items that are in a different state on Trakt
- if an item is being added/removed, at the same time the history will be synced too

If for some reason an item's rating was synced to Trakt, but its history wasn't, on the subsequent runs the history will be ignored. The approach I took for this is the following because IMDb doesn't have an equivalent to Trakt history.

To verify this is what happened with your rating/history, remove the rating for an item on Trakt and do a sync. The rating and history should be synced together during that sync run.

**Comment by rafae667** [comment]
Thank you for the explanation. Also, thank you so much for the repo. Great work.
I'm not able to understand the code and I'm not a developer. Fortunately I was able to make this work. 

I was just wondering if it wasn't supposed to sync IMDB ratings for both Trakt ratings and history.
I guess it's best to leave it as is. I doesn't bothers me since I'll continue using IMDB. Trakt is just for integrate the watchlists in Kodi.

**Comment by cecobask** [comment]
I’m glad that I could help you sync your IMDb library to Trakt. Unfortunately, with the current implementation the ratings and history are tightly coupled. I’ll look into separating the history sync into its own flow and push an update soon. You can star and watch the repository to see when I update it.

That’s exactly my use case too! 🙂 I’m using Kodi as my media player. It integrates nicely with Trakt, but I still mostly use IMDb for finding movies and creating lists.
