### ISSUE TITLE
Cannot find headless browser in actions

### ISSUE THREAD

**Issue by aktur** [cecobask/imdb-trakt-sync#42]
After latest fork syncing, my github sync action fails with the error
<img width="1238" alt="image" src="https://github.com/cecobask/imdb-trakt-sync/assets/5919960/f9802a69-cd08-4fa1-bc7d-99359d4eba59">

why I'm getting this error in the GitHub runner? Locally it is OK.

**Comment by cecobask** [comment]
Hi @aktur, this is really strange because the GitHub runner comes with a Google Chrome browser pre-installed.
I experienced the same issue in the beginning, but then it stopped happening - not sure what fixed it.
To make sure there is a browser in place, I added a manual installation step before the sync workflow runs.
Please let me know if that resolved the issue for you 🙂

**Comment by cecobask** [comment]
Hi again, I think I know why the sync workflow is failing for you. I believe it's because you haven't set the `SYNC_TIMEOUT` and `IMDB_TRACE` variables. Try setting every variable and running it again :+1:

**Comment by aktur** [comment]
Yes, indeed this was the case. I’ve have missed it as the action hasn’t complain about them, as opposite to IMDB_EMAIL and IMDB_PASSWORD. Thanks for your help, much appreciated!

**Comment by cecobask** [comment]
I got caught by the same issue initially. The trace and timeout configuration values are not essential for the sync to run as it should fall back to default values, but I didn’t realise it sets their values to empty. This caused weird behaviour in the app and it was difficult to catch. I will address that problem next!
