### ISSUE TITLE
Emails about login from IMDb.

### ISSUE THREAD

**Issue by aktur** [cecobask/imdb-trakt-sync#47]
Since the last update, I have been receiving emails from IMDb about logins with my password from new locations. While this is expected due to the new access method using username and password, logging in should not be necessary because I am only syncing a public watchlist. I am aware of another project, [Radarr](https://github.com/Radarr/Radarr/), which can sync a public watchlist without requiring a login.

Perhaps it is worth checking out?

**Comment by cecobask** [comment]
Hi @aktur, I recently changed the auth flow of the syncer. This was done to reduce the effort of maintaining repository secrets.

Previously you had to log in to the IMDb website and extract a couple of cookies with your browser’s developer tools. This had to be done every time your cookies expired, typically 2-3 times a year. The new approach for authentication requires your email and password, then the syncer automates the rest for you. In other words, you don’t have to worry about updating repository secrets anymore.

The project depends on the user being authenticated to scrape information about the user such as username, user id, watchlist id, list ids. Without authentication, these parameters will have to be provided to the syncer via configuration (environment variables, yaml file, command line flags). This increases the complexity for new users and takes more time to set up.

I’m aware of the spammy emails from IMDb about new logins from multiple locations. This expected because of the nature of GitHub runners. These are the workarounds that I can think of:
- set up an email filter on your email client for this type of emails
- self host GitHub runner/s and authentication will always happen from the location of your runner/s
- run the syncer locally instead of using GitHub Actions
