### ISSUE TITLE
Error running sync action: "error scraping trakt pin code: pin code not found"

### ISSUE THREAD

**Issue by EdRyan** [cecobask/imdb-trakt-sync#5]
I followed the instructions in the README about setting up the environment variables for GitHub Actions in a forked repository.  When manually running the "sync" action in GitHub on my forked repository, I get the following output:

```
Run go run cmd/imdb-trakt-sync/main.go
go: downloading github.com/joho/godotenv v1.4.0
go: downloading github.com/PuerkitoBio/goquery v1.8.0
go: downloading github.com/andybalholm/cascadia v1.3.1
go: downloading golang.org/x/net v0.0.0-20210916014120-12bc252f5db8
2022/11/08 19:30:56 error scraping trakt pin code: pin code not found
exit status 1
Error: Process completed with exit code 1.
```

**Comment by cecobask** [comment]
This looks like an issue with one of the Trakt environment variables / repository secrets.
Please check that the `TRAKT_USERNAME` / `TRAKT_PASSWORD` / `TRAKT_CLIENT_ID` / `TRAKT_CLIENT_SECRET` secrets are set to valid values. Make sure the `TRAKT_USERNAME` is not set to your email address, it has to be set to your actual username.

Let me know if that resolves the issue for you 👍🏻

**Comment by mseroczynski** [comment]
I've encountered the exact same issue, all of the values provided are correct.

**Comment by cecobask** [comment]
@mseroczynski, when fetching the Trakt PIN code, I encountered that issue in only one scenario. It usually happens when the credentials for Trakt were incorrect and the http redirect after logging in wasn’t leading to the page with the PIN code.

I couldn’t reproduce it in any other scenario. If you’ve got free time and want to look into this issue, feel free to open a pull request. I can help with debugging if necessary!

**Comment by ronin712** [comment]
I'm having this issue, and my log is identical to EdRyan's.  I don't mind helping debug if you want to walk me through what you need.

**Comment by cecobask** [comment]
@ronin712, thanks a lot for the initiative!
Let’s schedule a Google Meet slot when you have free time. We can communicate via email in order not to spam here. My email is baskski@gmail.com ⚡️

**Comment by cecobask** [comment]
I've updated the documentation to address the pin code issue in this commit https://github.com/cecobask/imdb-trakt-sync/commit/2e089e39a0e69706a08ac07f2fdc3ec0712bf524. Thanks to @ronin712 for helping me debug!

The issue appears when a Trakt API app hasn't been authorized/approved and the user is prompted to take action. This doesn't normally happen if the app has been approved. Since the solution to this issue can be fixed by the user while setting up their app, I have included a step in the instructions to address this. Fixing it through code can be a bit tricky/hacky and I won't be implementing this functionality for now.

All you need to do is click on the `Authorize` button on your API app's user interface at https://trakt.tv/oauth/applications!

cc: @mseroczynski, @EdRyan

**Comment by gergeo86** [comment]
wherre to put pin code which appears after i press authorize in trakt api?

**Comment by cecobask** [comment]
> wherre to put pin code which appears after i press authorize in trakt api?

@gergeo86, you can ignore the PIN code value you see after authorizing your Trakt API app. The action of authorizing marks your app as approved and that’s the goal of doing this.

**Comment by gergeo86** [comment]
keep having problem though.
![Screenshot (91)](https://user-images.githubusercontent.com/34986844/204683421-87ce6582-c261-4fac-a017-f61ff4f7bbda.png)

**Comment by cecobask** [comment]
@gergeo86, I added a permanent fix that should eliminate the problem with pin codes. Please, sync your fork, rerun the sync workflow and let me know if it all works fine for you.

**Comment by gergeo86** [comment]
still error.i fact i sync fork but it shows error too .in secrets the values are with "TRAKT_CLIENT_ID=" or just the letters/numbers after the"="?
![Screenshot (71)](https://user-images.githubusercontent.com/34986844/205387830-187cbede-7f98-40f6-98c1-4b4ac49d3294.png)
![Screenshot (72)](https://user-images.githubusercontent.com/34986844/205388447-5f1a3a79-a239-441a-a9aa-42370760cd77.png)

**Comment by cecobask** [comment]
@gergeo86, the Trakt secrets can be found in your API apps on the Trakt settings page. This is how you should be creating new secrets:
![1F26A1BA-E257-4339-AFB8-A392301D84D6](https://user-images.githubusercontent.com/32335835/205436553-f494d104-026a-4ab2-89b6-9ee2c070f07a.png)

**Comment by gergeo86** [comment]
still error ....pfffff....i can't understand what i am doing wrong .....

**Comment by cecobask** [comment]
@gergeo86, send me an email to baskski@gmail.com. We can arrange a timeslot and I'll help you set it up 👍🏻
