### ISSUE TITLE
Sync Error

### ISSUE THREAD

**Issue by BardaktakiAdam** [cecobask/imdb-trakt-sync#55]
Hi, it's me again. Sorry for disturbing you every time. I might be able to help you with those error screenshots, hopefully. Today I updated the fork and ran the action, again I got the error. Also, I would like to ask if there is a way to sync the fork automatically. Thank you so much @cecobask 

![image](https://github.com/user-attachments/assets/7facd210-9494-4825-8a4f-fd29222b6583)

**Comment by BardaktakiAdam** [comment]
![image](https://github.com/user-attachments/assets/57902549-05c8-4692-8669-12c6b262e411)

**Comment by cecobask** [comment]
Hi @BardaktakiAdam, 

I don't recommend you to automatically syncing your fork. Let's say you've set up your fork to suit your needs and everything works flawlessly. What if one day the original repository introduces breaking changes, which is very likely to happen in the future, and your fork automatically syncs them? Then you end up with broken sync workflows and must figure out what changed to make it all work again. If you didn't automatically sync, you'd keep using the version of the source code in your fork and potential breaking changes wouldn't impact you.

In the first screenshot, it looks like you're using `credentials` authentication method for IMDb. If you keep seeing the captcha error, you can switch to using `cookies` auth method. Once the cookies expire, your sync workflow will stop working and you'll have to update the cookies. However, this usually takes a few months until it happens.

In the second screenshot I can't tell what happened because `IMDB_TRACE` is probably disabled. You can set it to `true` for me to see more details of what happened.

**Comment by BardaktakiAdam** [comment]
Thank you for the information @cecobask 

I have updated the cookies again and IMDB_TRACE is true. The problem is still the same I guess. 

![image](https://github.com/user-attachments/assets/133d99fa-46b0-4dbf-9958-b38e231bdd7e)

**Comment by cecobask** [comment]
After checking your [latest sync workflow](https://github.com/BardaktakiAdam/imdb-trakt-sync/actions/runs/9939196505/job/27463783366) I saw that it's stuck determining what the outcome of your IMDb authentication which shouldn't happen if you've set `IMDB_AUTH` to cookies. Please, check your configuration carefully.
This is an example of my configuration when using cookies:
```
ITS_IMDB_AUTH=cookies
ITS_IMDB_COOKIEATMAIN=XXX
ITS_IMDB_COOKIEUBIDMAIN=XXX
ITS_IMDB_TRACE=true
ITS_SYNC_MODE=full
ITS_SYNC_HISTORY=true
ITS_SYNC_RATINGS=true
ITS_SYNC_WATCHLIST=true
ITS_TRAKT_CLIENTID=XXX
ITS_TRAKT_CLIENTSECRET=XXX
ITS_TRAKT_EMAIL=XXX
ITS_TRAKT_PASSWORD=XXX
```
