### ISSUE TITLE
error unmarshalling trakt auth codes response: unexpected end of JSON input

### ISSUE THREAD

**Issue by kotatrader** [cecobask/imdb-trakt-sync#6]
Getting this error and cannot get sync to finish

**Comment by cecobask** [comment]
I suspect something is wrong with one or more of the Trakt repository secrets.
I was planning on implementing more robust error handling with richer logs in the coming weeks.
Until then, try to play around with the value you've set for your fork's repository secrets as the problem is almost certainly there.

**Comment by kotatrader** [comment]
Thanks. Managed to get it to work by inputing the correct IMDB watchlist IDs (that's what was breaking the run)

**Comment by gergeo86** [comment]
same problem .cant get it work. @kotatrader kotatrader what and where exactly did you put the  imdb watchlist id?

**Comment by cecobask** [comment]
https://trakt.tv and part of their APIs are currently down, folks.
When I improve the logging of `imdb-trakt-sync` I'll make sure to report whether the Trakt API is available, so nobody will have to wonder if their configuration is faulty or the problem is elsewhere.
In this case, you can rest assured the problem is certainly with Trakt, I'm having failing sync since last night.
Just wait for Trakt to complete their maintenance and syncing will work again 👍🏻 
<img width="818" alt="image" src="https://user-images.githubusercontent.com/32335835/207091671-31e0df5d-accc-412c-ba72-f2d7d4a50999.png">
