### ISSUE TITLE
Failure hydrating imdb client

### ISSUE THREAD

**Issue by C4illin** [cecobask/imdb-trakt-sync#8]
```json
{
  "level": "fatal",
  "ts": "2023-01-06T12:08:13Z",
  "caller": "syncer/syncer.go:92",
  "msg": "failure hydrating imdb client",
  "error": "failure fetching trakt item id: unknown trakt item type season",
  "stacktrace": "github.com/cecobask/imdb-trakt-sync/pkg/syncer.(*Syncer).Run\n\t/home/runner/work/imdb-trakt-sync/imdb-trakt-sync/pkg/syncer/syncer.go:92\nmain.main\n\t/home/runner/work/imdb-trakt-sync/imdb-trakt-sync/cmd/syncer/main.go:8\nruntime.main\n\t/opt/hostedtoolcache/go/1.18.9/x64/src/runtime/proc.go:250"
}
```

Any idea what might be wrong? I tried refreshing all secrets but with no avail

**Comment by cecobask** [comment]
HI @C4illin, thank you for reporting that issue!

It can happen when you've rated or added tv show seasons to a list on Trakt.
This is an example JSON response from Trakt that includes a season. You can see that the show has an IMDb id, but seasons don't have a unique identifier for IMDb. It is the identifier that I'm using to map IMDb and Trakt entries, and finally perform syncing:
```
[
  {
    "rank": 1,
    "id": 778973361,
    "listed_at": "2023-01-06T18:31:36.000Z",
    "notes": null,
    "type": "season",
    "season": {
      "number": 5,
      "ids": {
        "trakt": 3954,
        "tvdb": 490110,
        "tmdb": 3578,
        "tvrage": null
      }
    },
    "show": {
      "title": "Breaking Bad",
      "year": 2008,
      "ids": {
        "trakt": 1388,
        "slug": "breaking-bad",
        "tvdb": 81189,
        "imdb": "tt0903747",
        "tmdb": 1396,
        "tvrage": 18164
      }
    }
  },
  ...
]
```
For now, on IMDb you cannot add tv show seasons to lists or rate them. I doubt this will ever change.
Due to this fact, syncing functionality for seasons between IMDb and Trakt won't be possible.
Your existing and future tv show season list entries and ratings will be ignored by imdb-trakt-sync.

In a moment I will add a commit to handle Trakt seasons in case someone gets this error in the future.
Feel free to express any concerns, feedback or comments here ✌️

**Comment by C4illin** [comment]
Thanks for the answer!
So I don't need to do anything to make the error go away other than updating to the latest?

**Comment by cecobask** [comment]
Yep, that's everything you need to do 🙂
Let me know if that doesn't fix it for you. I tried replicating it locally and it worked 👍🏻

**Comment by C4illin** [comment]
Yup it fixed it, thanks!

**Comment by rafae667** [comment]
After syncing the fix it stopped having successful syncs. I don't know what happened. My fork is up to date.

**Comment by cecobask** [comment]
@rafae667, the first thing I’d do after syncing your fork is to compare the repository secrets list with the one in the instructions.

Each secret is of specific format which must be followed. Recently, I made a change regarding the `TRAKT_USERNAME` secret. You need to replace it with a new one called `TRAKT_EMAIL`.

After double checking all secrets names and values are up to date, try manually syncing again. Let me know if you still have the same problem afterwards 👍🏻

**Comment by rafae667** [comment]
Yeah, that's it. I didn't notice that change. After changing that worked without a problem. Thank you 😄
